### ISSUE TITLE
I don’t understand what it is for and how it works.

### ISSUE THREAD

**Issue by selevo** [per1234/ThemeTest#2]
I see a list of keywords but I can change this in a text file, what does this archive do the author can make a video tutorial?

**Comment by per1234** [comment]
This repository contains documentation for the Arduino IDE's theme system and a dummy library that allows you to easily check how a custom theme looks.

I'm happy to provide more assistance, but this issue tracker is only for making bug reports or feature requests. For general support, the appropriate place is the Arduino forum. We can continue with any necessary discussion there.
