### ISSUE TITLE
Question: Change Color of own defined functions

### ISSUE THREAD

**Issue by hasenradball** [per1234/ThemeTest#3]
Hello can anyone help to change the color of a own defined function?
which keyword I had to search for in the Theme.txt file?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure I'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
3. Post a link to your forum thread here and I'll go check it out.
